### PR TITLE
Fixes a layout issue on the iPad, where there would sometimes be no margin on one side.

### PR DESCRIPTION
**Pull request by zenopolis**
On the iPad, when the popover arrow was on the leading or trailing side, there would be no margin between the edge of the popover and the collectionView.

### CODE REVIEW

**Comment by zenopolis** [comment]
Changes this...
Original

to this...
Fixed

**Comment by yosshi4486** [comment]
@zenopolis 
Thank you for the PR! Would you attach iPad's screenshots before and after the changes as a PR comment?

**Comment by zenopolis** [comment]
The original...
Original

After the fix...
Fixed

**Review by yosshi4486 — APPROVED** [review]
Looks good to me! I'll marge it.

**Pull request merged**
