### PR TITLE
feat(locale): implement danish localization

### PR DESCRIPTION
**Pull request by TimurBanax**

### CODE REVIEW

**Comment by TimurBanax** [comment]
@yosshi4486 Hey, wannna implement another langauge? Go ahead!

**Comment by yosshi4486** [comment]
@TimurBanax Thank you for your localization work 👍

Would you take screenshots of localized screens for review? (Don't mind test fails because they are caused by new generation unicode emojis. I gonna fix the problem in other pull request.)

**Comment by TimurBanax** [comment]
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 21 52
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 21 14
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 21 11
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 21 09
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 21 07
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 21 06
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 21 04
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 21 02
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 20 59
Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 01 22 04

Here you go!

**Comment by yosshi4486** [comment]
@TimurBanax Thank you! I'll merge it soon.

**Pull request merged**
